#!/usr/bin/env escript


main([PhpPath]) ->
  Root = filename:dirname(escript:script_name()),
  code:add_pathz(Root ++ "/ebin"),
  code:add_pathz(Root ++ "/../ebin"),
  code:add_pathz(Root ++ "/src"),
  [code:add_pathz(Path) || Path <- filelib:wildcard(Root ++ "/deps/*/ebin")],
  [code:add_pathz(Path) || Path <- filelib:wildcard(Root ++ "/../../*/ebin")],
  example_php:start(PhpPath),
  io:get_line("Example PHP launched\n");


main([]) ->
  io:format("Usage: ~s ~~/path/to/php-app/~n", [escript:script_name()]),
  ok.
